version: "3.9"

services:
#  backend:
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#
#  frontend:
#    build: ./web
#    ports:
#      - '3000:3000'
#    stdin_open: true
#    tty: true
#    depends_on:
#      - backend
  database:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=quiz
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
